# Dependencies
markdown:         redcarpet
highlighter:     true

# Permalinks
permalink:        pretty

# Setup
title:       Hai Lin
tagline:      'blog'
description:  'This is <a href="/about">Hai Lin</a>, a developer in New York.'
url:          http://hai-lin.com
baseurl:          '/'
paginate:         5

author:
  name:       'Hai Lin'
  email:      'hai@hai-lin.com'
  url:          http://hai-lin.com

# Custom vars
version:          1.0.0

github:
  repo:          https://github.com/Hai-Lin/hai-lin.github.com
